#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.

apt-get -y update
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=Y3puNlFBqvo&ab_channel=DrakeVEVO;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
